FROM {{ namespace }}/{{ image_prefix }}bifrost-base:{{ tag }}
MAINTAINER {{ maintainer }}
ENV container docker
RUN $(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ "$i" == "systemd-tmpfiles-setup.service" ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
RUN pip install -U ansible

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}
RUN yum install -y e2fsprogs && yum clean all
{% elif base_distro in ['ubuntu', 'debian'] %}
RUN apt-get install -y e2fsprogs && apt-get autoclean
{% endif %}

VOLUME [ "/sys/fs/cgroup" ]
VOLUME [ "/dev" ]
CMD [ "/sbin/init" ]
